theme: jekyll-theme-cayman
name: "Lars Holmberg"
title: "HTML and CSS"
description: "Assignments and Solutions"
repository: "k3larra/htmlcss"
plugins: ['jekyll-github-metadata']
baseurl: "/htmlcss"
excerpt_separator: <!--more-->
