theme: jekyll-theme-cayman
name: Lars Holmberg
title: Introduction to HTML and CSS
description: Assignments and Solutions
repository: "k3larra/htmlcss"
gems: ['jekyll-github-metadata']
url: https://k3larra.github.io/htmlcss/
