theme: jekyll-theme-cayman
name: "Lars Holmberg"
title: "HTML och CSS"
description: "Assignments and Solutions"
repository: "k3larra/htmlcss"
gems: ['jekyll-github-metadata']
baseurl: "/htmlcss"
excerpt_separator: <!--more-->
